    - name: Install MySQL Database
      apt: name={{ item }} state=present
      with_items:
        - mysql-server
        - mysql-client

    - name: Start MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create Application Database
      mysql_db:
        login_user: root
        login_password: ''
        db: "{{ db_name }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
          # login_unix_socket: '/var/lib/mysql/mysql.sock'

    - name: Create MySQL users
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_user_password }}"
        priv: '*.*:ALL'
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present

